const express=require('express'), path=require('path'), fs=require('fs'), os=require('os'), AdmZip=require('adm-zip');
const app=express(); app.use(express.json({limit:'4mb'})); app.use(express.static(path.join(__dirname,'public')));
const FAA=['https://registry.faa.gov/database/ReleasableAircraft.zip','https://registry.faa.gov/aircraftinquiry/ReleasableAircraft.zip'];
const CACHE=path.join(os.tmpdir(),'dispatchlink-faa.json'); let faaMem=null, faaAt=0; const DAY=86400000;
const clean=s=>String(s??'').trim();
function csvLine(s){let a=[],v='',q=false;for(let i=0;i<s.length;i++){let c=s[i];if(c==='"'){if(q&&s[i+1]==='"'){v+='"';i++;}else q=!q;}else if(c===','&&!q){a.push(v);v='';}else v+=c;}a.push(v);return a.map(clean)}
function csv(text){let ls=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean),h=csvLine(ls.shift());return ls.map(l=>{let x=csvLine(l),o={};h.forEach((k,i)=>o[k.trim()]=x[i]||'');return o})}
function field(o,names){let ks=Object.keys(o);for(const n of names){let k=ks.find(k=>k.toLowerCase().replace(/[ _-]/g,'')===n.toLowerCase().replace(/[ _-]/g,''));if(k)return clean(o[k])}return ''}
async function getbuf(url){let r=await fetch(url,{headers:{'User-Agent':'DispatchLink-iPad/1.1','Accept':'*/*'},signal:AbortSignal.timeout(90000)});if(!r.ok)throw Error(`FAA HTTP ${r.status}`);return Buffer.from(await r.arrayBuffer())}
async function loadFAA(force=false){if(!force&&faaMem&&Date.now()-faaAt<DAY*7)return faaMem;if(!force&&fs.existsSync(CACHE)){try{let st=fs.statSync(CACHE);if(Date.now()-st.mtimeMs<DAY*7){faaMem=JSON.parse(fs.readFileSync(CACHE));faaAt=Date.now();return faaMem}}catch{}}
 let buf,last;for(const u of FAA){try{buf=await getbuf(u);break}catch(e){last=e}} if(!buf)throw Error(`FAA registry download failed: ${last?.message||'unknown error'}`);
 let z=new AdmZip(buf), m=z.getEntry('MASTER.txt'), a=z.getEntry('ACFTREF.txt');if(!m||!a)throw Error('FAA registry ZIP is missing MASTER.txt or ACFTREF.txt');
 let refs=new Map();for(const r of csv(a.getData().toString('utf8'))){let code=field(r,['CODE']),make=field(r,['MFR','MANUFACTURER']),model=field(r,['MODEL']);if(code)refs.set(code,{make,model})}
 let out=[];for(const r of csv(m.getData().toString('utf8'))){let status=field(r,['STATUS CODE','STATUS']);if(status&&!['V','VALID'].includes(status.toUpperCase()))continue;let n=field(r,['N-NUMBER','N_NUMBER','N NUMBER']),code=field(r,['MFR MDL CODE','MFR_MDL_CODE','MFRMDLCODE']),x=refs.get(code)||{};if(n)out.push({tail:'N'+n.replace(/^N/i,''),make:x.make||'',model:x.model||'',serial:field(r,['SERIAL NUMBER','SERIAL']),year:field(r,['YEAR MFR','YEAR'])})}
 if(!out.length)throw Error('FAA registry loaded but contained no usable aircraft');faaMem=out;faaAt=Date.now();try{fs.writeFileSync(CACHE,JSON.stringify(out))}catch{}return out}
async function token(){let id=process.env.OPENSKY_CLIENT_ID,sec=process.env.OPENSKY_CLIENT_SECRET;if(!id||!sec)return null;let body=new URLSearchParams({grant_type:'client_credentials',client_id:id,client_secret:sec});let r=await fetch('https://auth.opensky-network.org/auth/realms/opensky-network/protocol/openid-connect/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body,signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error(`OpenSky authentication HTTP ${r.status}`);return (await r.json()).access_token}
async function states(){let t=await token().catch(()=>null),headers={'User-Agent':'DispatchLink-iPad/1.1'};if(t)headers.Authorization=`Bearer ${t}`;let r=await fetch('https://opensky-network.org/api/states/all',{headers,signal:AbortSignal.timeout(30000)});if(r.status===429)throw Error('OpenSky rate limit reached. Try again shortly.');if(!r.ok)throw Error(`OpenSky live feed HTTP ${r.status}`);return (await r.json()).states||[]}
async function hexInfo(h){try{let r=await fetch(`https://hexdb.io/api/v1/aircraft/${h}`,{signal:AbortSignal.timeout(10000)});return r.ok?await r.json():{}}catch{return {}}}
async function hexByReg(reg){try{let r=await fetch(`https://hexdb.io/reg-hex?reg=${encodeURIComponent(reg)}`,{signal:AbortSignal.timeout(10000)});if(!r.ok)return null;let j=await r.json();return clean(j.ModeS||j.hex).toLowerCase()||null}catch{return null}}
app.get('/api/health',(q,s)=>s.json({ok:true,name:'DispatchLink iPad',version:'1.1.0'}));
app.get('/api/config',(q,s)=>s.json({faaRegistry:true,liveProvider:'OpenSky + HexDB',openSkyCredentialsConfigured:!!(process.env.OPENSKY_CLIENT_ID&&process.env.OPENSKY_CLIENT_SECRET)}));
app.post('/api/faa/refresh',async(q,s)=>{try{let x=await loadFAA(true);s.json({ok:true,count:x.length})}catch(e){s.status(502).json({error:e.message})}});
app.get('/api/faa/random',async(q,s)=>{try{let x=await loadFAA(),mk=clean(q.query.make).toLowerCase(),md=clean(q.query.model).toLowerCase(),f=x.filter(a=>(!mk||a.make.toLowerCase().includes(mk))&&(!md||a.model.toLowerCase().includes(md)));if(!f.length)return s.status(404).json({error:'No FAA aircraft matched those make/model filters.'});let a={...f[Math.floor(Math.random()*f.length)],source:'FAA'};let hx=await hexByReg(a.tail);if(hx){let i=await hexInfo(hx);a.icao24=hx;a.operator=i.RegisteredOwners||i.Operator||i.OperatorFlagCode||'—';a.serial=a.serial||i.SerialNo||i.Serial||i.MSN||'—';a.year=a.year||i.YearBuilt||i.Year||'—'}s.json(a)}catch(e){s.status(502).json({error:e.message})}});
app.get('/api/global/random',async(q,s)=>{try{let st=await states();let hexes=st.filter(r=>r&&r[0]&&!r[8]).map(r=>r[0].toLowerCase()).sort(()=>Math.random()-.5).slice(0,600),pre=clean(q.query.prefix).toUpperCase(),mk=clean(q.query.make).toLowerCase(),md=clean(q.query.model).toLowerCase();for(const hx of hexes){let i=await hexInfo(hx),reg=clean(i.Registration).toUpperCase(),make=clean(i.Manufacturer),model=clean(i.Type||i.ICAOTypeCode);if((!pre||reg.startsWith(pre))&&(!mk||make.toLowerCase().includes(mk))&&(!md||model.toLowerCase().includes(md)))return s.json({tail:reg,make,model,serial:i.SerialNo||i.Serial||i.MSN||'—',year:i.YearBuilt||i.Year||'—',icao24:hx,operator:i.RegisteredOwners||i.Operator||i.OperatorFlagCode||'—',source:'OpenSky + HexDB'});}s.status(404).json({error:'No airborne aircraft matched those filters in the sampled live traffic.'})}catch(e){s.status(502).json({error:e.message})}});
app.post('/api/parse-fr24',(req,res)=>{const t=String(req.body.text||''),lines=t.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),rows=[],rx=/(\d{1,2}\s+[A-Za-z]{3}\s+\d{2,4}).*?\b([A-Z0-9]{3,4})\b.*?\b([A-Z][A-Z0-9-]{2,9})\b.*?\b([A-Z0-9]{2,3}\d{1,5}[A-Z]?)\b.*?\b([A-Z]{3,4})\b.*?\b([A-Z]{3,4})\b.*?(\d{2}:?\d{2})\s*(?:Z)?.*?(\d{2}:?\d{2})/i;for(const l of lines){const m=l.match(rx);if(m)rows.push({dof:m[1],ac:m[2].toUpperCase(),reg:m[3].toUpperCase(),flight:m[4].toUpperCase(),dep:m[5].toUpperCase(),arr:m[6].toUpperCase(),std:m[7]+'Z',sta:m[8]+'Z'})}res.json({rows,parsed:rows.length})});
app.listen(process.env.PORT||3000,'0.0.0.0',()=>console.log('DispatchLink iPad 1.1 ready'));
